---
- name: Deploy Kubernetes Application to EKS
  hosts: k8s   # Replace with your EKS master node or bastion host
  gather_facts: yes
  become: yes

  tasks:
    - name: Copy deployment.yaml to target node
      copy:
        src: /var/lib/jenkins/workspace/petstore/deployment.yaml
        dest: /home/ubuntu/deployment.yaml
        mode: '777'

    - name: Generate kubeconfig for EKS
      command: aws eks update-kubeconfig --region ap-south-1 --name Vijay
      environment:
        AWS_PROFILE: default   # adjust if you use a specific IAM profile
      become: no

    - name: Apply Deployment using kubectl
      command: kubectl apply -f /home/ubuntu/deployment.yaml
      become: no
      register: kubectl_output

    - name: Show kubectl output
      debug:
        var: kubectl_output.stdout
