---
- name: Deploy Kubernetes Application
  hosts: k8s  # Replace with your target Kubernetes master host or group
  gather_facts: yes
  become: yes

  tasks:
    - name: Copy deployment.yaml to Kubernetes master
      copy:
        src: /var/lib/jenkins/workspace/petstore/deployment.yaml
        dest: /home/ubuntu/deployment.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Ensure .kube directory exists
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0700'

    - name: Copy kubeconfig to remote node
      copy:
        src: /var/lib/jenkins/.kube/config   # Adjust if your kubeconfig is elsewhere
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Apply Deployment using kubectl
      command: kubectl apply -f /home/ubuntu/deployment.yaml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      become: no
      register: kubectl_output

    - name: Show kubectl output
      debug:
        var: kubectl_output.stdout
